import re

# 所有pacakge sdk
ALL_PACKAGE_SDK = {'com.google.android.gms.ads': 'Google AdMob',
              'com.google.android.gms.ads.APPLICATION_ID': 'Google AdMob (Meta-data ID)',
              'com.facebook.ads': 'Facebook Audience Network', 'com.amazon.device.ads': 'Amazon Publisher Services',
              'com.mopub': 'MoPub (已被AppLovin收购, 老应用常见)',
              'com.yahoo.mobile.client.android': 'Yahoo Flurry Ads',
              'com.bytedance.sdk.openadsdk': 'Pangle (穿山甲/字节跳动)', 'com.qq.e.ads': 'Tencent GDT (腾讯广点通)',
              'com.qq.e.comm': 'Tencent GDT (腾讯广点通基础组件)', 'com.baidu.mobads': 'Baidu Union (百度联盟)',
              'com.kwad.sdk': 'Kuaishou (快手联盟)', 'com.huawei.hms.ads': 'Huawei Ads Kit (华为广告服务)',
              'com.sigmob.sdk': 'Sigmob (国内常见下沉市场广告SDK)', 'cn.domob.android.ads': 'Domob (多盟)',
              'applovin.sdk.key': 'AppLovin (Meta-data Key)', 'com.applovin': 'AppLovin',
              'com.unity3d.services.ads': 'Unity Ads', 'com.unity3d.ads': 'Unity Ads', 'com.ironsource': 'ironSource',
                   'com.vungle.warren': 'Vungle (Liftoff)', 'com.vungle.publisher': 'Vungle (老版本)',
                   'com.chartboost.sdk': 'Chartboost', 'com.tapjoy': 'Tapjoy', 'com.adcolony': 'AdColony',
                   'com.mbridge.msdk': 'Mintegral (Mobvista/汇量科技)', 'com.mintegral.msdk': 'Mintegral (老版本包名)',
                   'com.startapp.sdk': 'StartApp (历史上侵入性弹窗极多)',
                   'com.startapp.android.publish': 'StartApp (老版本)',
                   'com.airpush.android': 'Airpush (古早流氓广告之王，见之必杀)',
                   'com.leadbolt': 'Leadbolt (常用于静默下载和通知栏广告)', 'com.revmob': 'RevMob', 'com.inmobi': 'InMobi',
                   'com.fyber': 'Fyber', 'com.outbrain': 'Outbrain (常用于网页伪装文章推荐)', 'com.taboola': 'Taboola',
                   'com.sms.intercept.sdk': '短信拦截盗刷SDK（监听拦截银行验证码，配合无障碍服务完成支付盗刷，100%恶意）',
                   'com.sms.forward.sdk': '短信转发SDK（自动转发用户短信到黑产服务器，窃取验证码、交易通知）',
                   'com.payment.hijack.sdk': '支付界面劫持SDK（监听支付APP启动，覆盖虚假弹窗窃取密码/验证码）',
                   'com.accessibility.cheat.sdk': '无障碍劫持SDK（模拟用户点击完成自动转账、广告刷量，金融盗刷核心组件）',
                   'com.silent.install.sdk': '静默安装SDK（无需用户授权，后台自动安装推广APK/恶意软件）',
                   'com.auto.download.sdk': '静默下载器SDK（后台无感知下载恶意安装包、推广软件，绕过安全提醒）',
                   'com.remote.control.sdk': '远控木马SDK（远程控制设备、执行指令、窃取文件，间谍软件核心组件）',
                   'com.keylogger.sdk': '键盘记录器SDK（记录用户所有按键输入，窃取密码、支付信息）',
                   'com.clipboard.monitor.sdk': '剪贴板监听SDK（实时监听剪贴板，窃取银行卡号、密码、验证码）',
                   'com.spy.camera.sdk': '后台偷拍SDK（无感知调用相机偷拍，上传隐私照片/视频）',
                   'com.spy.microphone.sdk': '后台窃听SDK（无感知调用麦克风录音，监听用户通话/环境声音）',
                   'com.device.lock.sdk': '锁机勒索SDK（锁定用户设备，篡改锁屏密码，索要赎金）',
                   'com.privacy.steal.sdk': '全量隐私窃取SDK（批量窃取通讯录、短信、定位、相册，用于黑产数据贩卖）',
                   'com.contacts.steal.sdk': '通讯录窃取SDK（读取用户联系人信息，用于精准诈骗、垃圾短信推送）',
                   'com.location.track.sdk': '定位跟踪SDK（后台高频采集用户定位，实时上传恶意服务器）',
                   'com.adcolony.sdk': 'AdColony（海外高风险广告SDK，强制无跳过视频弹窗，无感知收集设备信息）',
                   'com.adhub.sdk': 'AdHub (曾被曝光植入恶意代码，导致 CamScanner 等应用被 Google Play 下架)',
                   'com.applovin.sdk': 'AppLovin（广告聚合SDK，多次因隐私违规、诱导点击被多国监管处罚）',
                   'com.chartboost': 'Chartboost (游戏插屏广告 SDK，强制全屏弹窗，诱导点击恶意链接)',
                   'com.ironsource.sdk': 'ironSource (侵入性广告 SDK，后台强制自启，过度收集用户隐私数据)',
                   'com.konfety.sdk': 'Konfety (大规模广告欺诈 SDK，日均发起数十亿次欺诈广告请求)',
                   'com.kuaiya.ad.sdk': '快压广告SDK（臭名昭著的捆绑推广SDK，静默安装垃圾软件，弹窗泛滥）',
                   'com.mintegral.sdk': 'Mintegral（汇量科技，多次因隐私违规、诱导点击、广告欺诈被处罚）',
                   'com.vungle.sdk': 'Vungle (视频广告 SDK，恶意锁屏广告、后台保活，隐私数据违规收集)',
                   'com.beiye.ad.sdk': '倍业广告SDK（工信部通报，违规收集个人信息、窗口乱跳转、诱导点击）',
                   'com.zhongjian.ad.sdk': '众简广告SDK（工信部通报，违规收集个人信息、SDK信息公示不到位）',
                   'com.shenshi.ad.sdk': '神蓍广告SDK（网信办通报，违规收集用户个人信息，无明确隐私规则）',
                   'com.lewany.aggregation.sdk': '乐玩聚合SDK（工信部通报，违规收集个人信息、SDK信息公示不到位）',
                   'com.dashu.game.sdk': '大树游戏SDK（工信部通报，违规超范围收集个人信息）',
                   'com.haima.cloud.game.sdk': '海马云游戏SDK（工信部通报，超范围收集个人信息、SDK信息公示不到位）',
                   'com.uni.ad.sdk': 'uni-AD原生广告SDK（工信部通报，超范围收集个人信息、信息窗口乱跳转）',
                   'com.liandao.sdk': '联道SDK（工信部通报，超范围收集个人信息、SDK信息公示不到位）',
                   'com.menta.android.sdk': 'MentaAndroid SDK（工信部通报，超范围收集个人信息）',
                   'com.pangle.sdk': '穿山甲SDK（违规集成版本存在后台自启、隐私过度收集问题）',
                   'com.gdt.sdk': '广点通SDK（违规集成版本存在隐私过度收集、诱导点击行为）',
                   'com.baidu.ad.sdk': '百度广告SDK（历史多次因违规收集隐私、强制弹窗被监管通报）',
                   'com.down.loader.sdk': '通用静默下载器 SDK (黑产专用，后台无感知下载安装恶意 APK)',
                   'com.install.silent.sdk': '静默安装 SDK (无需用户授权，自动安装推广 / 恶意应用)',
                   'com.bundle.install.sdk': '捆绑安装 SDK (重打包应用专用，捆绑推广垃圾应用)',
                   'com.auto.install.sdk': '自动安装 SDK (黑产常用，监听应用安装事件，批量安装推广包)',
                   'com.apk.downloader.sdk': 'APK 下载器 SDK (后台静默下载恶意安装包，绕过用户确认)',
                   'com.market.promote.sdk': '应用推广 SDK (黑灰产专用，无授权刷量、静默安装推广应用)',
                   'com.update.forced.sdk': '强制更新 SDK (伪装成应用更新，实则安装恶意推广软件)',
                   'com.91.helper.sdk': '91 助手 SDK (老牌捆绑推广 SDK，静默安装垃圾应用)',
                   'com.pp.assistant.sdk': 'PP 助手 SDK (违规捆绑安装，后台静默推广应用)',
                   'com.wandoujia.ad.sdk': '豌豆荚广告 SDK (历史多次因捆绑安装、静默推广被监管处罚)',
                   'com.discount.game.sdk': '0.1 折手游 SDK (工信部通报，违规收集个人信息、诱导下载)',
                   'com.gamefan.sdk': '游戏 Fan SDK (工信部通报，违规超范围收集个人信息)',
                   'com.adjust.sdk': 'Adjust（归因SDK，过度收集用户设备信息，违规跟踪用户行为）',
                   'com.avazu.sdk': 'Avazu (艾维邑动 SDK，黑产常用，恶意推广、隐私窃取行为频发)',
                   'com.crashlytics.android': 'Crashlytics (崩溃统计 SDK，历史多次出现隐私数据违规收集、泄露问题)',
                   'com.flurry.android': 'Flurry Analytics（数据分析SDK，过度收集用户隐私，历史多次数据泄露）',
                   'com.mobvista.sdk': 'Mobvista (汇量科技旗下 SDK，多次因隐私违规、诱导点击被处罚)',
                   'com.tiktok.ad.sdk': 'TikTok Ads SDK (部分违规版本存在隐私过度收集、后台自启问题)',
                   'com.yeahmobi.sdk': 'Yeahmobi (易点天下 SDK，历史出现恶意推广、隐私违规收集问题)',
                   'com.ahmyth.rat': 'AhMyth Android RAT（全球黑产最常用的开源远控 SDK）',
                   'ahmyth.android.client': 'AhMyth Android RAT（全球黑产最常用的开源远控 SDK）',
                   'com.ahmyth.mine': 'AhMyth Android RAT（全球黑产最常用的开源远控 SDK）',
                   'com.spynote.sdk': 'SpyNote 远控木马 SDK', 'com.spynote.client': 'SpyNote 远控木马 SDK',
                   'in.androidx.spynote': 'SpyNote 远控木马 SDK', 'com.droidjack.client': 'DroidJack 远控 SDK',
                   'com.droidjack.server': 'DroidJack 远控 SDK', 'com.oray.sunlogin.evil': '破解版向日葵远控恶意变种',
                   'com.sunlogin.remote': '破解版向日葵远控恶意变种', 'com.mspy.sdk': 'mSpy 商业间谍监控 SDK（黑产广泛滥用）',
                   'com.mspy.client': 'mSpy 商业间谍监控 SDK（黑产广泛滥用）',
                   'com.android.system.mspy': 'mSpy 商业间谍监控 SDK（黑产广泛滥用）', 'com.flexispy.sdk': 'FlexiSPY 间谍 SDK',
                   'com.flexispy.android': 'FlexiSPY 间谍 SDK', 'com.system.service.flexispy': 'FlexiSPY 间谍 SDK',
                   'com.thetruthspy.sdk': 'TheTruthSpy 监听 SDK', 'com.android.thetruthspy': 'TheTruthSpy 监听 SDK',
                   'com.qt.tingting': '国内黑产「窃听猫」SDK', 'com.wt.tingjian': '国内黑产「窃听猫」SDK',
                   'com.kidlogger.sdk': 'KidLogger 键盘记录 SDK（黑产滥用）',
                   'com.kidlogger.android': 'KidLogger 键盘记录 SDK（黑产滥用）',
                   'com.spyrix.keylogger': 'Spyrix 键盘记录 SDK', 'com.android.system.spyrix': 'Spyrix 键盘记录 SDK',
                   'com.keylogger.android': '开源黑产 Android 键盘记录 SDK',
                   'com.android.keyboard.record': '开源黑产 Android 键盘记录 SDK',
                   'com.system.input.keylogger': '开源黑产 Android 键盘记录 SDK',
                   'com.screen.record.sdk': '黑产「静默屏幕录制」SDK', 'com.android.screen.capture': '黑产「静默屏幕录制」SDK',
                   'com.system.screen.recorder': '黑产「静默屏幕录制」SDK', 'com.camera.spy.sdk': '黑产「静默相机」偷拍 SDK',
                   'com.android.camera.secret': '黑产「静默相机」偷拍 SDK',
                   'com.system.camera.service': '黑产「静默相机」偷拍 SDK',
                   'com.mspy.screenrecorder': 'mSpy/FlexiSPY 内置模块',
                   'com.flexispy.camera.capture': 'mSpy/FlexiSPY 内置模块',
                   'com.android.system.lock': '黑产「一键锁机」勒索 SDK', 'com.locker.ransom': '黑产「一键锁机」勒索 SDK',
                   'com.doublelocker.sdk': 'DoubleLocker 勒索软件 SDK', 'com.file.steal.sdk': '黑产「文件窃取者」SDK',
                   'com.system.file.stealer': '黑产「文件窃取者」SDK', 'com.spynote.file.grabber': '黑产「文件窃取者」SDK'}

# package SDK 风险类型
ALL_PACKAGE_TYPE = {'com.google.android.gms.ads': ['COMMON_SDk'],
                'com.google.android.gms.ads.APPLICATION_ID': ['COMMON_SDk'],
                'com.facebook.ads': ['OVERSEAS_HIGH_RISK_SDK', 'COMMON_SDk'], 'com.amazon.device.ads': ['COMMON_SDk'],
                'com.mopub': ['OVERSEAS_HIGH_RISK_SDK', 'COMMON_SDk'],
                'com.yahoo.mobile.client.android': ['COMMON_SDk'], 'com.bytedance.sdk.openadsdk': ['COMMON_SDk'],
                'com.qq.e.ads': ['MID_RISK_SDK', 'ROGUE_SDK', 'COMMON_SDk'], 'com.qq.e.comm': ['COMMON_SDk'],
                'com.baidu.mobads': ['COMMON_SDk'], 'com.kwad.sdk': ['COMMON_SDk'],
                'com.huawei.hms.ads': ['COMMON_SDk'], 'com.sigmob.sdk': ['COMMON_SDk'],
                'cn.domob.android.ads': ['COMMON_SDk'], 'applovin.sdk.key': ['COMMON_SDk'],
                'com.applovin': ['COMMON_SDk'], 'com.unity3d.services.ads': ['COMMON_SDk'],
                'com.unity3d.ads': ['HIGH_RISK_SKD', 'OVERSEAS_HIGH_RISK_SDK', 'COMMON_SDk'],
                    'com.ironsource': ['COMMON_SDk'], 'com.vungle.warren': ['COMMON_SDk'],
                    'com.vungle.publisher': ['COMMON_SDk'], 'com.chartboost.sdk': ['COMMON_SDk'],
                    'com.tapjoy': ['OVERSEAS_HIGH_RISK_SDK', 'COMMON_SDk'], 'com.adcolony': ['COMMON_SDk'],
                    'com.mbridge.msdk': ['COMMON_SDk'], 'com.mintegral.msdk': ['COMMON_SDk'],
                    'com.startapp.sdk': ['HIGH_RISK_SKD', 'COMMON_SDk'],
                    'com.startapp.android.publish': ['HIGH_RISK_SKD', 'COMMON_SDk'],
                    'com.airpush.android': ['HIGH_RISK_SKD', 'COMMON_SDk'], 'com.leadbolt': ['HIGH_RISK_SKD', 'COMMON_SDk'],
                    'com.revmob': ['HIGH_RISK_SKD', 'COMMON_SDk'], 'com.inmobi': ['HIGH_RISK_SKD', 'COMMON_SDk'],
                    'com.fyber': ['HIGH_RISK_SKD', 'COMMON_SDk'],
                    'com.outbrain': ['HIGH_RISK_SKD', 'OVERSEAS_HIGH_RISK_SDK', 'COMMON_SDk'],
                    'com.taboola': ['HIGH_RISK_SKD', 'OVERSEAS_HIGH_RISK_SDK', 'COMMON_SDk'],
                    'com.sms.intercept.sdk': ['EXTREMELY_HIGH_RISK'], 'com.sms.forward.sdk': ['EXTREMELY_HIGH_RISK'],
                    'com.payment.hijack.sdk': ['EXTREMELY_HIGH_RISK'],
                    'com.accessibility.cheat.sdk': ['EXTREMELY_HIGH_RISK'],
                    'com.silent.install.sdk': ['EXTREMELY_HIGH_RISK'], 'com.auto.download.sdk': ['EXTREMELY_HIGH_RISK'],
                    'com.remote.control.sdk': ['EXTREMELY_HIGH_RISK'], 'com.keylogger.sdk': ['EXTREMELY_HIGH_RISK'],
                    'com.clipboard.monitor.sdk': ['EXTREMELY_HIGH_RISK'], 'com.spy.camera.sdk': ['EXTREMELY_HIGH_RISK'],
                    'com.spy.microphone.sdk': ['EXTREMELY_HIGH_RISK'],
                    'com.device.lock.sdk': ['EXTREMELY_HIGH_RISK', 'DEVICE_LOCK_SDK'],
                    'com.privacy.steal.sdk': ['EXTREMELY_HIGH_RISK'], 'com.contacts.steal.sdk': ['EXTREMELY_HIGH_RISK'],
                    'com.location.track.sdk': ['EXTREMELY_HIGH_RISK'], 'com.adcolony.sdk': ['HIGH_RISK_SKD'],
                    'com.adhub.sdk': ['HIGH_RISK_SKD'], 'com.applovin.sdk': ['HIGH_RISK_SKD'],
                    'com.chartboost': ['HIGH_RISK_SKD', 'OVERSEAS_HIGH_RISK_SDK'], 'com.ironsource.sdk': ['HIGH_RISK_SKD'],
                    'com.konfety.sdk': ['HIGH_RISK_SKD'], 'com.kuaiya.ad.sdk': ['HIGH_RISK_SKD', 'BUNDLED_SDK'],
                    'com.mintegral.sdk': ['HIGH_RISK_SKD', 'OVERSEAS_HIGH_RISK_SDK'], 'com.vungle.sdk': ['HIGH_RISK_SKD'],
                    'com.beiye.ad.sdk': ['MID_RISK_SDK', 'ROGUE_SDK'],
                    'com.zhongjian.ad.sdk': ['MID_RISK_SDK', 'ROGUE_SDK'],
                    'com.shenshi.ad.sdk': ['MID_RISK_SDK', 'ROGUE_SDK'],
                    'com.lewany.aggregation.sdk': ['MID_RISK_SDK', 'ROGUE_SDK'],
                    'com.dashu.game.sdk': ['MID_RISK_SDK', 'ROGUE_SDK'],
                    'com.haima.cloud.game.sdk': ['MID_RISK_SDK', 'ROGUE_SDK'],
                    'com.uni.ad.sdk': ['MID_RISK_SDK', 'ROGUE_SDK'], 'com.liandao.sdk': ['MID_RISK_SDK', 'ROGUE_SDK'],
                    'com.menta.android.sdk': ['MID_RISK_SDK', 'ROGUE_SDK'], 'com.pangle.sdk': ['MID_RISK_SDK', 'ROGUE_SDK'],
                    'com.gdt.sdk': ['MID_RISK_SDK', 'ROGUE_SDK'], 'com.baidu.ad.sdk': ['MID_RISK_SDK', 'ROGUE_SDK'],
                    'com.down.loader.sdk': ['BUNDLED_SDK'], 'com.install.silent.sdk': ['BUNDLED_SDK'],
                    'com.bundle.install.sdk': ['BUNDLED_SDK'], 'com.auto.install.sdk': ['BUNDLED_SDK'],
                    'com.apk.downloader.sdk': ['BUNDLED_SDK'], 'com.market.promote.sdk': ['BUNDLED_SDK'],
                    'com.update.forced.sdk': ['BUNDLED_SDK'], 'com.91.helper.sdk': ['BUNDLED_SDK'],
                    'com.pp.assistant.sdk': ['BUNDLED_SDK'], 'com.wandoujia.ad.sdk': ['BUNDLED_SDK'],
                    'com.discount.game.sdk': ['ROGUE_SDK'], 'com.gamefan.sdk': ['ROGUE_SDK'],
                    'com.adjust.sdk': ['OVERSEAS_HIGH_RISK_SDK'], 'com.avazu.sdk': ['OVERSEAS_HIGH_RISK_SDK'],
                    'com.crashlytics.android': ['OVERSEAS_HIGH_RISK_SDK'], 'com.flurry.android': ['OVERSEAS_HIGH_RISK_SDK'],
                    'com.mobvista.sdk': ['OVERSEAS_HIGH_RISK_SDK'], 'com.tiktok.ad.sdk': ['OVERSEAS_HIGH_RISK_SDK'],
                    'com.yeahmobi.sdk': ['OVERSEAS_HIGH_RISK_SDK'], 'com.ahmyth.rat': ['REMOTE_CONTROL_SDK'],
                    'ahmyth.android.client': ['REMOTE_CONTROL_SDK'], 'com.ahmyth.mine': ['REMOTE_CONTROL_SDK'],
                    'com.spynote.sdk': ['REMOTE_CONTROL_SDK'], 'com.spynote.client': ['REMOTE_CONTROL_SDK'],
                    'in.androidx.spynote': ['REMOTE_CONTROL_SDK'], 'com.droidjack.client': ['REMOTE_CONTROL_SDK'],
                    'com.droidjack.server': ['REMOTE_CONTROL_SDK'], 'com.oray.sunlogin.evil': ['REMOTE_CONTROL_SDK'],
                    'com.sunlogin.remote': ['REMOTE_CONTROL_SDK'], 'com.mspy.sdk': ['SPY_SDK'],
                    'com.mspy.client': ['SPY_SDK'], 'com.android.system.mspy': ['SPY_SDK'], 'com.flexispy.sdk': ['SPY_SDK'],
                    'com.flexispy.android': ['SPY_SDK'], 'com.system.service.flexispy': ['SPY_SDK'],
                    'com.thetruthspy.sdk': ['SPY_SDK'], 'com.android.thetruthspy': ['SPY_SDK'],
                    'com.qt.tingting': ['SPY_SDK'], 'com.wt.tingjian': ['SPY_SDK'], 'com.kidlogger.sdk': ['KEYLOGGER_SDK'],
                    'com.kidlogger.android': ['KEYLOGGER_SDK'], 'com.spyrix.keylogger': ['KEYLOGGER_SDK'],
                    'com.android.system.spyrix': ['KEYLOGGER_SDK'], 'com.keylogger.android': ['KEYLOGGER_SDK'],
                    'com.android.keyboard.record': ['KEYLOGGER_SDK'], 'com.system.input.keylogger': ['KEYLOGGER_SDK'],
                    'com.screen.record.sdk': ['CAMERA_SPY_SDK'], 'com.android.screen.capture': ['CAMERA_SPY_SDK'],
                    'com.system.screen.recorder': ['CAMERA_SPY_SDK'], 'com.camera.spy.sdk': ['CAMERA_SPY_SDK'],
                    'com.android.camera.secret': ['CAMERA_SPY_SDK'], 'com.system.camera.service': ['CAMERA_SPY_SDK'],
                    'com.mspy.screenrecorder': ['CAMERA_SPY_SDK'], 'com.flexispy.camera.capture': ['CAMERA_SPY_SDK'],
                    'com.android.system.lock': ['DEVICE_LOCK_SDK'], 'com.locker.ransom': ['DEVICE_LOCK_SDK'],
                    'com.doublelocker.sdk': ['DEVICE_LOCK_SDK'], 'com.file.steal.sdk': ['DEVICE_LOCK_SDK'],
                    'com.system.file.stealer': ['DEVICE_LOCK_SDK'], 'com.spynote.file.grabber': ['DEVICE_LOCK_SDK']}
